[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/",
  "@solmate/=lib/solmate/src/",
  "foundry-devops/=lib/foundry-devops/src/"
]


fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" }
]
[fuzz]
runs = 256

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"



